version = 0.1
[default.deploy.parameters]
stack_name = "akshay-rekognition"
resolve_s3 = true
s3_prefix = "akshay-rekognition"
region = "us-east-1"
profile = "aws_sol"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
